defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "work"
    values:
      layout: "work"
  - scope:
      path: ""
    values:
      layout: basic


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
