defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "work"
    values:
      layout: "work"
  - scope:
      path: ""
      type: "file"
    values:
      layout: "file"
  - scope:
      path: ""
    values:
      layout: basic

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-katex

collections:
  essays:
    collections_dir: _essays
    output: true
    permalink: :collection/:title/
  designs:
    collections_dir: _designs
    output: true
    permalink: :collection/:title/
  otherwork:
    collections_dir: _otherwork
    output: true
    permalink: :collection/:title/
  posts:
    permalink: :year/:month/:day/:title/
  files:
    collections_dir: _directory
    output: true
    permalink: :collection/:title/

baseurl: /rubytest

# markdown: kramdown
# kramdown:
#   math_engine: mathjax
